export const dateType = 'YYYY-MM-DD';
export const timeType = 'YYYY-MM-DD hh:mm:ss';

export const leftMenuIcon: any = {
  流量分析: 'icon-14',
  搜索分析: 'icon-28',
  装修分析: 'icon-38',
  商品分析: 'icon-18',
  关联工具: 'icon-6',
  服务分析: 'icon-5',
  物流分析: 'icon-32',
  行业竞争: 'icon-36',
  店铺竞争: 'icon-2',
  商品竞争: 'icon-22',
  推荐数据: 'icon-29',
  问答分析: 'icon-30',
  内容数据: 'icon-16',
  广告效果: 'icon-15',
  小店渠道数据: 'icon-17',
  大屏作战: 'icon-39',
  整体概览: 'icon-12',
  流量概况: 'icon-8',
  来源分析: 'icon-9',
  动线分析: 'icon-10',
  内容投放: 'icon-11',
  问答数据: 'icon-13',
  售前客服: 'icon-19',
  售后服务: 'icon-20',
  促销工具: 'icon-33',
  预售活动: 'icon-7',
  活动作战: 'icon-23',
  监控作战: 'icon-25',
  商品洞察: 'icon-31',
  驾驶舱: 'icon-35',
  品类洞察: 'icon-3',
  配置中心: 'icon-26',
  服务概况: 'icon-37',
  售前服务: 'icon-4',
  物流管家: 'icon-1',
  品牌竞争: 'icon-34',
  效能提升: 'icon-14',
  异常雷达: 'icon-4',
  内容概况: 'icon-18',
  内容沉淀: 'icon-5',
  营销活动: 'icon-23',
  报表DIY: 'icon-diy',
  常见问题: 'icon-uniE901'
};
