#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
#. "$(dirname "$0")/common.sh"

# [ -n "$CI" ] && exit 0

# Format and submit code according to lintstagedrc.js configuration
npx lint-staged
# lerna run --concurrency 1 --stream precommit --since HEAD --exclude-dependents
# yarn lint-staged
